# Generated by Django 3.1.7 on 2021-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210413_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
    ]
