# Generated by Django 3.1.7 on 2021-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210414_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sign',
            field=models.CharField(default='No sign', max_length=15, null=True),
        ),
    ]
